name: Build and Test -> Compute coverage -> Release if requested

on:
  push:
    branches:
      - master
    paths: 
      - "src/test/**"

jobs:
    name: Test -> Compute coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 8
          architecture: x64
      - name: Build and test
        run: mvn clean test -DskipTests=false -P run-coveralls jacoco:report coveralls:report -DrepoToken=${{ secrets.coveralls_repo_token }}

