name: Update artifact downloads

on:
  push:
    branches:
      - master
    paths: 
      - ".github/workflows/update artifact downloads.yml"

#on:
#  schedule:
#    - cron: "30 0 21 * *"

jobs:
        
  update-artifact-downloads:
    name: Update artifact downloads
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Clear Camo cache and update README.md
        run: |
          curl -X PURGE https://camo.githubusercontent.com/07a0d977b53e6c2bf8412197f02f792018a6fc77da2d28f1db8744815be87603/68747470733a2f2f7777772e6275726e696e67776176652e6f72672f67656e657261746f72732f67656e65726174652d6275726e696e67776176652d61727469666163742d646f776e6c6f6164732d62616467652e7068703f747970653d73766726617274696661637449643d636f7265 
          git config user.name "Burningwave"
          git config user.email "info@burningwave.org"
          git pull origin ${{github.ref}}
          sed -i "s/type=svgggggggggggg/type=svg/w changelog.txt" ./README.md
          if ! [ -s changelog.txt ]; then
             sed -r -i "s%type=svg%type=svgg%" ./README.md;
          fi          
          git commit -am "Artifact downloads automatic update"
          git push
