name: Build and test (experimental branch)

on:
  schedule:
      - cron: "0 0-23/4 * * *"
#     - cron: "0 17 * * 5"
#     - cron: "0 4,16 30 9 *"    
#     - cron: "30 15 * * 5"
jobs:
    
  build-and-test-with-Java-8-and-later:
    name: Build -> Test (JVM ${{ matrix.java }}, ${{ matrix.os }})
    strategy:
      fail-fast: true
      max-parallel: 15
      matrix:
        architecture: [x64, x64, x64, x64, x64, x64, x64]
        os: [ubuntu-latest, macOS-latest, windows-latest]
        java: [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18-ea]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: experimental 
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          architecture: ${{ matrix.architecture }}
      - name: Build and test with final version JDK
        run: mvn -B clean test -DskipTests=false --file pom.xml
  
  compute-coverage:
    name: Compute coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 8
          architecture: x64
      - name: Build and test
        run: mvn clean test -DskipTests=false -P run-coveralls jacoco:report coveralls:report -DrepoToken=${{ secrets.coveralls_repo_token }}
  
