name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
    
  build-and-test-on-Java-8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        java-package: jdk  
    - name: Build & test
      run: mvn -B package -DskipTests=false -DjavadocExecutable.relativePath=../bin/javadoc --file pom.xml

  build-and-test-on-Java-9:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 9
      uses: actions/setup-java@v1
      with:
        java-version: 9
        java-package: jdk  
    - name: Build & test
      run: mvn -B package -Dproject.jdk.version=9 -DskipTests=false --file pom.xml

  build-and-test-on-Java-10:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 10
      uses: actions/setup-java@v1
      with:
        java-version: 10
        java-package: jdk  
    - name: Build & test
      run: mvn -B package -Dproject.jdk.version=10 -DskipTests=false --file pom.xml
  
  build-and-test-on-Java-11:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        java-package: jdk  
    - name: Build & test
      run: mvn -B package -Dproject.jdk.version=11 -DskipTests=false --file pom.xml
  
  build-and-test-on-Java-12:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 12
      uses: actions/setup-java@v1
      with:
        java-version: 12
        java-package: jdk  
    - name: Build & test
      run: mvn -B package -Dproject.jdk.version=10 -DskipTests=false --file pom.xml
  
  build-and-test-on-Java-13:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 13
      uses: actions/setup-java@v1
      with:
        java-version: 13
        java-package: jdk  
    - name: Build & test
      run: mvn -B package -Dproject.jdk.version=13 -DskipTests=false --file pom.xml
  
  build-and-test-on-Java-14:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
        java-package: jdk  
    - name: Build & test
      run: mvn -B package -Dproject.jdk.version=14 -DskipTests=false --file pom.xml
