name: Build, test, package and check coverage 

on:
  watch:
    types: [started]

jobs:
  authorize: 
    runs-on: ubuntu-latest

    steps:
    - uses: octokit/request-action@v2.0.0
      with:
        route: GET /repos/:repository/collaborators/${{ github.actor }}
        repository: ${{ github.repository }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
  with-Java-8:
    needs: [authorize]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        java-package: jdk  
    - name: Build & test
      run: mvn -B clean package -DskipTests=false -DjavadocExecutable.relativePath=../bin/javadoc --file pom.xml

  with-Java-9:
    needs: [with-Java-8]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 9
      uses: actions/setup-java@v1
      with:
        java-version: 9
        java-package: jdk  
    - name: Build & test
      run: mvn -B clean package -Dproject.jdk.version=9 -DskipTests=false --file pom.xml

  with-Java-10:
    needs: [with-Java-9]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 10
      uses: actions/setup-java@v1
      with:
        java-version: 10
        java-package: jdk  
    - name: Build & test
      run: mvn -B clean package -Dproject.jdk.version=10 -DskipTests=false --file pom.xml
  
  with-Java-11:
    needs: [with-Java-10]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        java-package: jdk  
    - name: Build & test
      run: mvn -B clean package -Dproject.jdk.version=11 -DskipTests=false --file pom.xml
  
  with-Java-12:
    needs: [with-Java-11]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 12
      uses: actions/setup-java@v1
      with:
        java-version: 12
        java-package: jdk  
    - name: Build & test
      run: mvn -B clean package -Dproject.jdk.version=12 -DskipTests=false --file pom.xml
  
  with-Java-13:
    needs: [with-Java-12]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 13
      uses: actions/setup-java@v1
      with:
        java-version: 13
        java-package: jdk  
    - name: Build & test
      run: mvn -B clean package -Dproject.jdk.version=13 -DskipTests=false --file pom.xml
  
  with-Java-14:
    needs: [with-Java-13]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
        java-package: jdk  
    - name: Build & test
      run: mvn -B clean package -Dproject.jdk.version=14 -DskipTests=false --file pom.xml
 
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    needs: [with-Java-14]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 8
          architecture: x64
      - name: Build project
        run: mvn clean test -DskipTests=false -P run-coveralls jacoco:report coveralls:report -DrepoToken=${{ secrets.coveralls_repo_token }}
